version: '2'
services:
    docs:
        build: ./_docker/asciidoctor
        container_name: docs-asciidoctor
        image: my-docs
        restart: always
        volumes:
            - ./:/docs
        ports:
          - 35729:35729

    server:
        image: httpd:2.4
        container_name: docs-www
        ports:
          - 8080:80
        volumes:
          -  ./:/usr/local/apache2/htdocs/
         #- ./_docker/http/conf:/usr/local/apache2/conf/
